export const quotes = ["don't be sad, we are still going to the moon",
  "don't do it",
  "'Yo don't worry about it' - do kwon",
  "we're going to the moon",
  "'poetry' - do kwon",
  'not investment advice',
  'fly me to the moon',
  "'You are a sad, strange little man, and you have my pity' - Toy Story",
  'sometimes i feel like im just drifting through space, floating aimlessly with no direction',
  'Don’t bet against the moon',
]
